#!/bin/bash
export \
SERVER_PORT=6655 \
SERVER_DOMAIN_NAME='localhost' \
PROXY_SERVER_PORT=6006 \
SERVER_APP_RESTARTER__LAUNCH_FILE='build/server.js' \
SERVER_APP_RESTARTER__PORT=6601 \
SERVER_BROWSER_RESTARTER__PORT=6602 \
SERVER_STATIC_WATCHER__PORT=6603 \
SERVER_STATIC_WATCHER__SUCCESS_CALLBACK='node scripts/request-refresh-browser-script.js' \
SERVER_BUILD_FOLDER='build' \
INDEX_FILE_NAME='index.ejs' \
SERVER_SRC_FOLDER='src/server' \
URL_APP_RELOAD_SERVER='http://localhost:6601' \
URL_BROWSER_RELOAD_SERVER='http://localhost:6602' \